import { DateTime } from "luxon";

const masterDashboardList = [{
    id: 'jobsReceived',
    title: 'Jobs Received',
    // x:2,
    // y:2,
    // w:2,
    // h:2,
    draggableHandle: ".dragHandle",
    inputs: {
        settings: true,
        allCompany: true,
        assignedClients: true,
        accountManager: true,
        relationType: true,
        billRate: true,
        jobType: true,
        clientType: true,
        graph: true,
        graphValue: 'line',
        graphName: 'line',
        datesDiv: true,
    },
    defaultValues: {
        graphMonthsSelected: "90",
        dateSelected: 'thisWeek',
        fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
        toDate: DateTime.now().toFormat('MM-dd-yyyy'),
        modifiedTitle: 'Jobs Received',
        companyType: '',
        assignedClientIds: [],
        assignedClientNames: [],
        accountManagerIds: [],
        accountManagerNames: [],
        userIds: [],
        userNames: [],
        clientIds: [],
        clientNames: [],
        relationshipType: '',
        billRate: '',
        jobType: '',
        clientType: ''
    }
},
{
    id: 'starts',
    title: 'Starts',
    draggableHandle: ".dragHandle",
    inputs: {
        settings: true,
        allCompany: true,
        assignedClients: true,
        accountManager: true,
        relationType: true,
        billRate: true,
        jobType: true,
        graph: true,
        graphValue: 'line',
        graphName: 'line',
        datesDiv: true,
    },
    defaultValues: {
        graphMonthsSelected: "90",
        dateSelected: 'thisWeek',
        fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
        toDate: DateTime.now().toFormat('MM-dd-yyyy'),
        modifiedTitle: 'Starts',
        companyType: '',
        assignedClientIds: [],
        assignedClientNames: [],
        accountManagerIds: [],
        accountManagerNames: [],
        userIds: [],
        userNames: [],
        clientIds: [],
        clientNames: [],
        relationshipType: '',
        billRate: '',
        jobType: ''
    }
},
// {
//     id: 'headCount',
//     title: 'Head Count',
//     draggableHandle: ".dragHandle",
//     inputs: {
//         settings: true,
//         allCompany: true,
//         assignedClients: true,
//         userIds: true,
//         relationType: true,
//         billRate: true,
//         placementType: true,
//         graph: true,
//         graphValue: 'line',
//         graphName: 'line',
//         datesDiv: false,
//     },
//     defaultValues: {
//         graphMonthsSelected: "90",
//         modifiedTitle: 'Head Count',
//         companyType: '',
//         assignedClientIds: [],
//         assignedClientNames: [],
//         accountManagerIds: [],
//         accountManagerNames: [],
//         userIds: [],
//         userNames: [],
//         clientIds: [],
//         clientNames: [],
//         relationshipType: '',
//         billRate: '',
//         placementType: ''
//     }
// },
// {
//     id: 'pendingStarts',
//     title: 'Pending Starts',
//     draggableHandle: ".dragHandle",
//     inputs: {
//         settings: true,
//         allCompany: true,
//         assignedClients: true,
//         accountManager: true,
//         relationType: true,
//         billRate: true,
//         jobType: true,
//         graph: false,
//         graphValue: '',
//         graphName: '',
//         datesDiv: false,
//     },
//     defaultValues: {
//         graphMonthsSelected: "90",
//         modifiedTitle: 'Pending Starts',
//         companyType: '',
//         assignedClientIds: [],
//         assignedClientNames: [],
//         accountManagerIds: [],
//         accountManagerNames: [],
//         userIds: [],
//         userNames: [],
//         clientIds: [],
//         clientNames: [],
//         relationshipType: '',
//         billRate: '',
//         jobType: ''
//     }
// },
// {
//     id: 'gms',
//     title: 'GM$',
//     draggableHandle: ".dragHandle",
//     inputs: {
//         settings: true,
//         allCompany: true,
//         assignedClients: true,
//         userIds: true,
//         relationType: true,
//         jobCategory: true,
//         graph: false,
//         graphValue: '',
//         graphName: '',
//         datesDiv: false,
//     },
//     defaultValues: {
//         graphMonthsSelected: "90",
//         dateSelected: 'thisWeek',
//         fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
//         toDate: DateTime.now().toFormat('MM-dd-yyyy'),
//         modifiedTitle: 'GM$',
//         companyType: '',
//         assignedClientIds: [],
//         assignedClientNames: [],
//         accountManagerIds: [],
//         accountManagerNames: [],
//         userIds: [],
//         userNames: [],
//         clientIds: [],
//         clientNames: [],
//         relationshipType: '',
//         jobCategory: '',
//         gmValue: 'hourly'
//     }
// },
{
    id: 'interviews',
    title: 'Interviews',
    datesDivInputs: {
        today: true,
        yesterday: true,
        nextWeek: true
    },
    inputs: {
        settings: true,
        allCompany: true,
        assignedClients: true,
        userIds: true,
        relationType: true,
        billRate: true,
        jobType: true,
        skills: true,
        jobTitle: true,
        graph: false,
        graphValue: '',
        graphName: '',
        datesDiv: true,
    },
    defaultValues: {
        dateSelected: 'thisWeek',
        fromDate: '',
        toDate: '',
        modifiedTitle: 'Interviews',
        companyType: '',
        assignedClientIds: [],
        assignedClientNames: [],
        accountManagerIds: [],
        accountManagerNames: [],
        userIds: [],
        userNames: [],
        clientIds: [],
        clientNames: [],
        relationshipType: '',
        billRate: '',
        jobType: '',
        skills: '',
        jobTitle: '',
    }
},
{
    id: 'offersReceived',
    title: 'Offers Received',
    datesDivInputs: {
        today: true,
        yesterday: true
    },
    inputs: {
        settings: true,
        allCompany: true,
        assignedClients: true,
        userIds: true,
        relationType: true,
        billRate: true,
        jobType: true,
        skills: true,
        jobTitle: true,
        graph: false,
        graphValue: '',
        graphName: '',
        datesDiv: true,
    },
    defaultValues: {
        dateSelected: 'thisWeek',
        fromDate: '',
        toDate: '',
        modifiedTitle: 'Offers Received',
        companyType: '',
        assignedClientIds: [],
        assignedClientNames: [],
        accountManagerIds: [],
        accountManagerNames: [],
        userIds: [],
        userNames: [],
        clientIds: [],
        clientNames: [],
        relationshipType: '',
        billRate: '',
        jobType: '',
        skills: '',
        jobTitle: '',
    }
},
{
    id: 'submissions',
    title: 'Submissions',
    Inputs: {
        today: true,
        yesterday: true
    },
    draggableHandle: ".dragHandle",
    inputs: {
        settings: true,
        allCompany: true,
        assignedClients: true,
        userIds: true,
        relationType: true,
        billRate: true,
        jobType: true,
        skills: true,
        jobTitle: true,
        graph: false,
        graphValue: '',
        graphName: '',
        datesDiv: true,
    },
    defaultValues: {
        graphMonthsSelected: "90",
        dateSelected: 'thisWeek',
        fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
        toDate: DateTime.now().toFormat('MM-dd-yyyy'),
        modifiedTitle: 'Submissions',
        companyType: '',
        assignedClientIds: [],
        assignedClientNames: [],
        accountManagerIds: [],
        accountManagerNames: [],
        userIds: [],
        userNames: [],
        clientIds: [],
        clientNames: [],
        relationshipType: '',
        billRate: '',
        jobType: '',
        skills: '',
        jobTitle: '',
    }
},
{
    id: 'jobsWithoutSubs',
    title: 'Jobs without Subs',
    draggableHandle: ".dragHandle",
    inputs: {
        settings: true,
        allCompany: true,
        assignedClients: true,
        userIds: true,
        relationType: true,
        billRate: true,
        jobType: true,
        clientType: true,
        graph: true,
        graphValue: 'pie',
        graphName: 'pie',
        datesDiv: true,
    },
    defaultValues: {
        graphMonthsSelected: "90",
        dateSelected: 'thisWeek',
        fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
        toDate: DateTime.now().toFormat('MM-dd-yyyy'),
        modifiedTitle: 'Jobs without Subs',
        companyType: '',
        assignedClientIds: [],
        assignedClientNames: [],
        accountManagerIds: [],
        accountManagerNames: [],
        userIds: [],
        userNames: [],
        clientIds: [],
        clientNames: [],
        relationshipType: '',
        billRate: '',
        jobType: ''
    }
},
// {
//     id: 'startsAndEnds',
//     title: 'Starts and Ends',
//     datesDiv: true,
//     draggableHandle: ".dragHandle",
//     inputs: {
//          settings: true,
//         allCompany: false,
//         assignedClients: false
//     },
//     defaultValues: {
//         graphMonthsSelected: "90",
//         dateSelected: 'thisWeek',
//         fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
//         toDate: DateTime.now().toFormat('MM-dd-yyyy'),
//         modifiedTitle: 'Starts and Ends',
//         companyType: '',
//         assignedClientIds: [],
//         assignedClientNames: [],
//         accountManagerIds: [],
//         accountManagerNames: [],
//         userIds: [],
//         userNames: [],
//         clientIds: [],
//         clientNames: [],
//         relationshipType: '',
//         billRate: ''
//     }
// },
{
    id: 'recruitersWOSubs',
    title: 'Recruiters w/o Subs',
    draggableHandle: ".dragHandle",
    inputs: {
        settings: true,
        allCompany: true,
        myTeam: true,
        graph: false,
        graphValue: '',
        graphName: '',
        datesDiv: true,
    },
    defaultValues: {
        graphMonthsSelected: "90",
        dateSelected: 'thisWeek',
        fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
        toDate: DateTime.now().toFormat('MM-dd-yyyy'),
        modifiedTitle: 'Recruiters w/o Subs',
        companyType: '',
        userIds: [],
        userNames: []
    }
},
{
    id: 'recruitersWOShortlists',
    title: 'Recruiters w/o Shortlists',
    draggableHandle: ".dragHandle",
    inputs: {
        settings: true,
        allCompany: true,
        myTeam: true,
        graph: false,
        graphValue: '',
        graphName: '',
        datesDiv: true,
    },
    defaultValues: {
        graphMonthsSelected: "90",
        dateSelected: 'thisWeek',
        fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
        toDate: DateTime.now().toFormat('MM-dd-yyyy'),
        modifiedTitle: 'Recruiters w/o Shortlists',
        companyType: '',
        userIds: [],
        userNames: []
    }
},
{
    id: 'recruitersWOInterviews',
    title: 'Recruiters w/o Interviews',
    draggableHandle: ".dragHandle",
    inputs: {
        settings: true,
        allCompany: true,
        myTeam: true,
        graph: false,
        graphValue: '',
        graphName: '',
        datesDiv: true,
    },
    defaultValues: {
        graphMonthsSelected: "90",
        dateSelected: 'thisWeek',
        fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
        toDate: DateTime.now().toFormat('MM-dd-yyyy'),
        modifiedTitle: 'Recruiters w/o Interviews',
        companyType: '',
        userIds: [],
        userNames: []
    }
},
{
    id: 'swsc24h',
    title: 'Submissions without status change in 24 hours',
    draggableHandle: ".dragHandle",
    inputs: {
        settings: true,
        allCompany: true,
        selectClients: true,
        relationType: true,
        billRate: true,
        jobType: true,
        skills: true,
        jobTitle: true,
        withOutStatus: true,
        graph: false,
        graphValue: 'line',
        graphName: 'line',
        datesDiv: true,
    },
    defaultValues: {
        graphMonthsSelected: "90",
        dateSelected: 'thisWeek',
        fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
        toDate: DateTime.now().toFormat('MM-dd-yyyy'),
        modifiedTitle: 'Client submissions without status change in 24 hours',
        companyType: '',
        assignedClientIds: [],
        assignedClientNames: [],
        accountManagerIds: [],
        accountManagerNames: [],
        userIds: [],
        userNames: [],
        clientIds: [],
        clientNames: [],
        relationshipType: '',
        billRate: '',
        jobType: '',
        withOutStatus: '1'
    } 
},
{
    id: 'aojwc',
    title: 'Assigned/Owned job without coverage',
    draggableHandle: ".dragHandle",
    inputs: {
        settings: true,
        allCompany: true,
        selectClients: true,
        relationType: true,
        billRate: true,
        jobType: true,
        graph: false,
        graphValue: 'line',
        graphName: 'line',
        datesDiv: true,
    },
    defaultValues: {
        graphMonthsSelected: "90",
        dateSelected: 'thisWeek',
        fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
        toDate: DateTime.now().toFormat('MM-dd-yyyy'),
        modifiedTitle: 'Assigned/Owned job without coverage',
        companyType: '',
        assignedClientIds: [],
        assignedClientNames: [],
        accountManagerIds: [],
        accountManagerNames: [],
        userIds: [],
        userNames: [],
        clientIds: [],
        clientNames: [],
        relationshipType: '',
        billRate: '',
        jobType: ''
    }
},
{
    id: 'scwsci3d',
    title: 'Shortlisted candidates without status change in 3 days',
    draggableHandle: ".dragHandle",
    inputs: {
        settings: true,
        allCompany: true,
        selectClients: true,
        relationType: true,
        billRate: true,
        jobType: true,
        graph: false,
        graphValue: 'line',
        graphName: 'line',
        datesDiv: true,
    },
    defaultValues: {
        graphMonthsSelected: "90",
        dateSelected: 'thisWeek',
        fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
        toDate: DateTime.now().toFormat('MM-dd-yyyy'),
        modifiedTitle: 'Shortlisted candidates without status change in 3 days',
        companyType: '',
        assignedClientIds: [],
        assignedClientNames: [],
        accountManagerIds: [],
        accountManagerNames: [],
        userIds: [],
        userNames: [],
        clientIds: [],
        clientNames: [],
        relationshipType: '',
        billRate: '',
        jobType: ''
    }
},
{
    id: 'iwsci5d',
    title: 'Interviews without Status change in 5 days',
    draggableHandle: ".dragHandle",
    inputs: {
        settings: true,
        allCompany: true,
        selectClients: true,
        relationType: true,
        billRate: true,
        jobType: true,
        graph: false,
        graphValue: 'line',
        graphName: 'line',
        datesDiv: true,
    },
    defaultValues: {
        graphMonthsSelected: "90",
        dateSelected: 'thisWeek',
        fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
        toDate: DateTime.now().toFormat('MM-dd-yyyy'),
        modifiedTitle: 'Interviews without Status change in 5 days',
        companyType: '',
        assignedClientIds: [],
        assignedClientNames: [],
        accountManagerIds: [],
        accountManagerNames: [],
        userIds: [],
        userNames: [],
        clientIds: [],
        clientNames: [],
        relationshipType: '',
        billRate: '',
        jobType: ''
    }
},
// {
//     id: 'eeoc',
//     title: 'EEOC',
//     height: 400,
//     width: 1130,
//     draggableHandle: ".dragHandle",
//     inputs: {
//         settings: false,
//         graph: true,
//         graphValue: 'doughnut',
//         graphName: 'doughnut',
//         canvasVals: ['Disability', 'Veteran', 'Gender', 'Ethnic'],
//         countVals: ["Professionals", "Submissions", "Interviews", "Starts"],
//         datesDiv: false,
//     },
//     defaultValues: {
//         graphMonthsSelected: "90",
//         dateSelected: 'thisWeek',
//         fromDate: DateTime.now().startOf('week').toFormat('MM-dd-yyyy'),
//         toDate: DateTime.now().toFormat('MM-dd-yyyy'),
//         modifiedTitle: 'EEOC',
//         companyType: '',
//         assignedClientIds: [],
//         assignedClientNames: [],
//         accountManagerIds: [],
//         accountManagerNames: [],
//         userIds: [],
//         userNames: [],
//         clientIds: [],
//         clientNames: [],
//         relationshipType: '',
//         billRate: '',
//         jobType: ''
//     }
// }
// {
//     id: 'tasks',
//     title: 'Task',
//     height: "calc(100vh - 120px)",
//     width: 360,
//     task: true,
//     inputs: {
//     },
//     defaultValues: {
//         modifiedTitle: 'Task'
//     }
// }
]

const getCategory = {
    "490": 'Accounting Finance',
    "463": 'Admin Clerical',
    "37": 'Call Center',
    "492": 'Clinical',
    "491": 'Creative Marketing',
    "39": 'Engineering',
    "494": 'Health IT',
    "493": 'Healthcare',
    "58": 'Human Resources',
    "102": 'Industrial',
    "59": 'Information Technology',
    "497": 'Lab',
    "63": 'Legal',
    "498": 'Pharma',
    "496": 'Professional',
    "72": 'Sales',
    "103": 'Scientific',
    "495": 'Supply Chain',

}

const graphMonths = [
    {
        value: "90",
        text: "3 mo",
        months: 3
    },
    {
        value: "180",
        text: "6 mo",
        months: 6
    },
    {
        value: "270",
        text: "9 mo",
        months: 9
    },
    {
        value: "365",
        text: "12 mo",
        months: 12
    }
]

export { masterDashboardList, getCategory, graphMonths };