const JobSector_Category = [ 
        { id : "2792", label : "Fashion"},
        { id : "2790", label : "Electronics"},
        { id : "2788", label : "Design & Creative"},
        { id : "2786", label : "Defence & Military"},
        { id : "2784", label : "Consultancy"},
        { id : "10", label : "Engineering"},
        { id : "11", label : "Financial Services"},
        { id : "12", label : "FMCG"},
        { id : "13", label : "Insurance"},
        { id : "14", label : "Graduate Roles"},
        { id : "15", label : "Health & Safety"},
        { id : "16", label : "Hospitality & Catering"},
        { id : "17", label : "HR & Personnel"},
        { id : "18", label : "IT"},
        { id : "19", label : "Legal"},
        { id : "1", label : "Accountancy"},
        { id : "2", label : "Accountancy (Qualified)"},
        { id : "3", label : "Admin & Secretarial"},
        { id : "2798", label : "Telecommunications"},
        { id : "4", label : "Automotive"},
        { id : "5", label : "Banking"},
        { id : "2796", label : "Medical & Nursing"},
        { id : "6", label : "Charity & Voluntary"},
        { id : "7", label : "Building & Construction"},
        { id : "2794", label : "Logistics Distribution & Supply Chain"},
        { id : "8", label : "Call Centre & Customer Service"},
        { id : "9", label : "Education & Training"},
        { id : "20", label : "Leisure & Sport"},
        { id : "21", label : "Marketing"},
        { id : "22", label : "Media"},
        { id : "23", label : "Public Sector & Government"},
        { id : "24", label : "Purchasing & Procurement"},
        { id : "25", label : "Recruitment Consultancy"},
        { id : "26", label : "Retail"},
        { id : "27", label : "Sales"},
        { id : "28", label : "Science & Research"},
        { id : "29", label : "Social Care"},
        { id : "2808", label : "Manufacturing & Production"},
        { id : "2806", label : "Property & Housing"},
        { id : "2804", label : "Pharmaceuticals"},
        { id : "30", label : "Transport & Rail"},
        { id : "31", label : "Other"},
        { id : "2802", label : "Internet & New Media"},
        { id : "2782", label : "Arts"},
        { id : "2780", label : "Agriculture Fishing & Forestry"},
        { id : "2812", label : "Utilities"},
        { id : "2778", label : "Advertising & PR"},
        { id : "2810", label : "Travel & Tourism"},
        { id : "2776", label : "Aerospace"},
        { id : "2818", label : "Energy & Renewables"},
        { id : "2816", label : "Executive & Management" }
    
];
 
const Job_CountryShortCode = [
    { id : "DE", label : "Germany"}, 
    { id : "PR", label : "Puerto Rico"}, 
    { id : "HK", label : "Hong Kong"}, 
    { id : "TW", label : "Taiwan"}, 
    { id : "PT", label : "Portugal"}, 
    { id : "TZ", label : "Tanzania"}, 
    { id : "DM", label : "Denmark"}, 
    { id : "LU", label : "Luxembourg"}, 
    { id : "HR", label : "Croatia"}, 
    { id : "HU", label : "Hungary"}, 
    { id : "LY", label : "Libya"}, 
    { id : "QA", label : "Qatar"}, 
    { id : "UE", label : "United Arab Emirates"}, 
    { id : "MA", label : "Malta"}, 
    { id : "MC", label : "Monaco"}, 
    { id : "MD", label : "Moldova"}, 
    { id : "ID", label : "Indonesia"}, 
    { id : "MH", label : "Marshall Islands"}, 
    { id : "YT", label : "Mayotte"}, 
    { id : "IE", label : "Ireland"}, 
    { id : "MK", label : "Macedonia"}, 
    { id : "US", label : "United States"}, 
    { id : "MM", label : "Myanmar"}, 
    { id : "EG", label : "Egypt"}, 
    { id : "AD", label : "Andorra"}, 
    { id : "MP", label : "Northern Mariana Islands"}, 
    { id : "IM", label : "Isle of Man"}, 
    { id : "MQ", label : "Martinique"}, 
    { id : "IN", label : "India"}, 
    { id : "ZA", label : "South Africa"}, 
    { id : "IQ", label : "Iraq"}, 
    { id : "IT", label : "Italy"}, 
    { id : "MX", label : "Mexico"}, 
    { id : "VA", label : "Vatican City (Holy See)"}, 
    { id : "MY", label : "Malaysia"}, 
    { id : "AN", label : "Angola"}, 
    { id : "MZ", label : "Mozambique"}, 
    { id : "ES", label : "Spain"}, 
    { id : "VE", label : "Venezuela"}, 
    { id : "AR", label : "Argentina"}, 
    { id : "AT", label : "Austria"}, 
    { id : "NA", label : "Namibia"}, 
    { id : "RE", label : "Reunion"}, 
    { id : "VI", label : "Virgin Islands (U.S.)"}, 
    { id : "AU", label : "Australia"}, 
    { id : "VN", label : "Vietnam"}, 
    { id : "NG", label : "Nigeria"}, 
    { id : "JD", label : "Jordan"}, 
    { id : "JE", label : "Jersey"}, 
    { id : "RO", label : "Romania"}, 
    { id : "NL", label : "Netherlands"}, 
    { id : "BB", label : "Barbados"}, 
    { id : "ZZ", label : "Rest of the world (other countries)"}, 
    { id : "NO", label : "Norway"}, 
    { id : "RS", label : "Serbia"}, 
    { id : "BD", label : "Bangladesh"}, 
    { id : "BE", label : "Belgium"}, 
    { id : "RU", label : "Russia"}, 
    { id : "BG", label : "Bulgaria"}, 
    { id : "JP", label : "Japan"}, 
    { id : "FO", label : "Faroe Islands"}, 
    { id : "BM", label : "Bermuda"}, 
    { id : "BN", label : "Brunei"}, 
    { id : "FR", label : "France"}, 
    { id : "NZ", label : "New Zealand"}, 
    { id : "SA", label : "Saudi Arabia"}, 
    { id : "BR", label : "Brazil"}, 
    { id : "SE", label : "Sweden"}, 
    { id : "SI", label : "Singapore"}, 
    { id : "GA", label : "Gabon"}, 
    { id : "SM", label : "San Marino"}, 
    { id : "GB", label : "United Kingdom"}, 
    { id : "CA", label : "Canada"}, 
    { id : "OM", label : "Oman"}, 
    { id : "GG", label : "Channel Islands"}, 
    { id : "GH", label : "Ghana"}, 
    { id : "CH", label : "Switzerland"}, 
    { id : "KR", label : "South Korea"}, 
    { id : "GP", label : "Guadeloupe"}, 
    { id : "GQ", label : "Equatorial Guinea"}, 
    { id : "CN", label : "China"}, 
    { id : "GR", label : "Greece"}, 
    { id : "CO", label : "Colombia"}, 
    { id : "GU", label : "Guam"}, 
    { id : "TH", label : "Thailand"}, 
    { id : "PE", label : "Peru"}, 
    { id : "CZ", label : "Czech Republic"}, 
    { id : "PH", label : "Philippines"}, 
    { id : "TN", label : "Tunisia"}, 
    { id : "PK", label : "Pakistan"}, 
    { id : "PL", label : "Poland"}, 
    { id : "LI", label : "Liechtenstein"}, 
    { id : "PM", label : "St. Pierre and Miquelon"}, 
    { id : "TR", label : "Turkey"}, 
    { id : "LK", label : "Sri Lanka" } 
];

export { JobSector_Category, Job_CountryShortCode  };
