// import { userLocalData } from "../userData";
// import {
//     ID_PLATFORM_DIRECT_SOURCING,
//     ID_PLATFORM_HIGH_VOLUME_HIRING,
//     ID_PLATFORM_TALENT_SOURCE,
//     ID_PLATFORM_STAFFING,
//     ID_PLATFORM_ADHOC,

//     ID_CORE_JOBS,
//     ID_CORE_CANDIDATES,
//     ID_CORE_CLIENTS,
//     ID_CORE_CONTACTS,

//     ID_ADDON_CAREER_PORTAL,
//     ID_ADDON_CHATBOT,
//     ID_ADDON_PROJECTS_TALENTPOOL,
//     ID_ADDON_REFERRAL,
//     ID_ADDON_SMS,
//     ID_ADDON_CHROME_EXTENSION,
//     ID_ADDON_PUBLIC_TALENT_CLOUD,
//     ID_ADDON_DOCUMENT_SIGNING,
//     ID_ADDON_PEOPLE_CONTACT,
//     ID_ADDON_PEOPLE_CANDIDATE,
//     ID_ADDON_SYSTEM_CHECKER,
//     ID_ADDON_IDIBU,
//     ID_ADDON_JOBTARGET,
//     ID_ADDON_JOB_ICON,

//     ID_SETTINGS_APPLICANTS,
//     ID_SETTINGS_COMMUNITY,
//     ID_SETTINGS_TALENTPOOL,
//     ID_SETTINGS_RESUMES,
//     ID_SETTINGS_PEOPLE,
//     ID_SETTINGS_FORMS,
//     ID_SETTINGS_CAMPAIGNS,
//     ID_SETTINGS_WORKFLOW,
//     ID_SETTINGS_EMAILBUILDER,
//     ID_SETTINGS_HIRING_WORKFLOW,
//     ID_SETTINGS_JOURNEYS,
//     ID_SETTINGS_EVALUTE,
//     ID_SETTINGS_SOVREN,
//     ID_SETTINGS_PEOPLE_LOCATION_ALL,
//     ID_SETTINGS_PEOPLE_LOCATION_US,
//     ID_SETTINGS_SENDGRID,
//     ID_SETTINGS_QUICK_ACTION,

//     ID_REPORTS_TALENT_COMMUNITY_INSIGHTS,
//     ID_REPORTS_EXECUTIVE_INSIGHTS,
//     ID_REPORTS_HIRING_INSIGHTS,
//     ID_REPORTS_SOURCING_INSIGHTS,
//     ID_REPORTS_PIPELINE_INSIGHTS,
//     ID_REPORTS_RECRUITER_ACTIVITY_INSIGHTS,
//     ID_REPORTS_CREATE_DASHBOARD,
//     ID_REPORTS_AI_DATA_ANALYST,
//     ID_REPORTS_CUSTOM_REPORT,
//     ID_REPORTS_OUTREACH_ACTIVITY,
//     ID_REPORTS_OUTREACH_KPI,
//     ID_REPORTS_LINKEDIN_VIEWED_PROFILES,

//     ID_ATS_BULLHORN,
//     ID_ATS_VOICEAI,
//     ID_ATS_AVIONTEAPI,
//     ID_ATS_JOBDIVA,




//     ID_ROLE_ADMIN_SETTINGS,
//     ID_ROLE_ADMIN_SETTINGS_USER,
//     ID_ROLE_ADMIN_SETTINGS_ROLE,

//     ID_ROLE_COMPANY_SETTINGS,
//     ID_ROLE_COMPANY_SETTINGS_BRAND,
//     ID_ROLE_COMPANY_SETTINGS_GOALS,
//     ID_ROLE_COMPANY_SETTINGS_CAREER_PORTAL,
//     ID_ROLE_COMPANY_SETTINGS_ORGANIZATION,
//     ID_ROLE_COMPANY_SETTINGS_SOURCES,
//     ID_ROLE_COMPANY_SETTINGS_SENDING_LIMIT,
//     ID_ROLE_COMPANY_SETTINGS_SEQUENCE_RULESET,
//     ID_ROLE_COMPANY_SETTINGS_COMMUNITY,
//     ID_ROLE_COMPANY_SETTINGS_REFERRAL,

//     ID_ROLE_DEVELOPER_SETTINGS,
//     ID_ROLE_DEVELOPER_SETTINGS_WEBHOOK,
//     ID_ROLE_DEVELOPER_SETTINGS_API,

//     ID_ROLE_APP_SETTINGS,
//     ID_ROLE_APP_SETTINGS_MESSAGE_TEMPLATES,
//     ID_ROLE_APP_SETTINGS_CUSTOM_FIELDS,
//     ID_ROLE_APP_SETTINGS_REASONS,
//     ID_ROLE_APP_SETTINGS_OPTION_BANKS,
//     ID_ROLE_APP_SETTINGS_DUPLICATE_SETTINGS,
//     ID_ROLE_APP_SETTINGS_SCORE,
//     ID_ROLE_APP_SETTINGS_GOALS,
//     ID_ROLE_APP_SETTINGS_HOLIDAY_SETTING,

//     ID_ROLE_JOB_MODULE,
//     ID_ROLE_JOB_ALLOW_TO_CREATE_NEW_JOB,
//     ID_ROLE_JOB_ALLOW_TO_DELETE_JOB,
//     ID_ROLE_JOB_ALLOW_TO_MERGE_JOBS,
//     ID_ROLE_JOB_ALLOW_TO_POST_JOBS_ON_INTERNAL_AND_EXTERNAL_SITES,

//     ID_ROLE_CANDIDATE_MODULE,
//     ID_ROLE_CANDIDATE_CAN_CREATE_NEW_CANDIDATE,
//     ID_ROLE_CANDIDATE_CAN_CREATE_TALENT_POOLS,
//     ID_ROLE_CANDIDATE_CAN_VIEW_EDIT_TALENT_POOLS_INCLUDING_PRIVATE,
//     ID_ROLE_CANDIDATE_CAN_SEARCH_IN_TALENT_COMMUNITY,
//     ID_ROLE_CANDIDATE_CAN_SEARCH_EXTERNAL_JOB_BOARDS,
//     ID_ROLE_CANDIDATE_CAN_SEARCH_PUBLIC_TALENT_POOL,

//     ID_ROLE_CONTACT_MODULE,
//     ID_ROLE_CONTACT_CAN_CREATE_NEW_CONTACT,
//     ID_ROLE_CONTACT_CAN_EDIT_CONTACT,
//     ID_ROLE_CONTACT_CAN_MERGE_CONTACT,
//     ID_ROLE_CONTACT_CAN_VIEW_TASKS_NOTES_ACTIVITY_LOGS_OF_ALL_USERS,
//     ID_ROLE_CONTACT_CAN_EDIT_TASKS_NOTES_ACTIVITY_LOGS_OF_ALL_USERS,
//     ID_ROLE_CONTACT_CAN_VIEW_CONTACT,

//     ID_ROLE_CLIENT_MODULE,
//     ID_ROLE_CLIENT_CAN_CREATE_NEW_CLIENT,
//     ID_ROLE_CLIENT_CAN_MERGE_CLIENTS,
//     ID_ROLE_CLIENT_CAN_VIEW_ALL_CLIENTS,
//     ID_ROLE_CLIENT_CAN_VIEW_ONLY_CLIENTS_ASSIGNED_TO_THEM,

//     ID_ROLE_EMAIL_AND_SMS,
//     ID_ROLE_EMAIL_AND_SMS_CAN_SEND_BULK_EMAIL,
//     ID_ROLE_EMAIL_AND_SMS_CAN_SEND_BULK_SMS,
//     ID_ROLE_EMAIL_AND_SMS_CAN_SEND_EMAIL_ON_BEHALF_OF_OTHER_USERS,
//     ID_ROLE_EMAIL_AND_SMS_CAN_SEND_SMS_ON_BEHALF_OF_OTHER_USERS,
//     ID_ROLE_EMAIL_AND_SMS_CAN_EDIT_VIEW_MESSAGE_TEMPLATES,
//     ID_ROLE_EMAIL_AND_SMS_CAN_EDIT_DELETE_MESSAGE_TEMPLATES,

//     ID_ROLE_PEOPLE,
//     ID_ROLE_PEOPLE_CAN_SEARCH_TALENT_DIRECTORY,
//     ID_ROLE_PEOPLE_CAN_ADD_EDIT_PERSONAS,
//     ID_ROLE_PEOPLE_CAN_REQUEST_EMAIL_CONTACT,
//     ID_ROLE_PEOPLE_CAN_REQUEST_MOBILE_CONTACT_,
//     ID_ROLE_PEOPLE_CAN_BULK_REQUEST_MOBILE_CONTACT,
//     ID_ROLE_PEOPLE_CAN_BULK_REQUEST_EMAIL_CONTACT,

//     ID_ROLE_ANALYTICS,
//     ID_ROLE_ANALYTICS_CAN_ACCESS_EXECUTIVE_INSIGHTS,
//     ID_ROLE_ANALYTICS_CAN_ACCESS_HIRING_INSIGHTS,
//     ID_ROLE_ANALYTICS_CAN_ACCESS_RECRUITER_ACTIVITY_INSIGHTS,
//     ID_ROLE_ANALYTICS_CAN_ACCESS_SOURCING_INSIGHTS,
//     ID_ROLE_ANALYTICS_CAN_ACCESS_APPLICANT_INSIGHTS,
//     ID_ROLE_ANALYTICS_CAN_ACCESS_TALENT_COMMUNITY_INSIGHTS,
//     ID_ROLE_ANALYTICS_CAN_ACCESS_PIPELINE_INSIGHTS,
//     ID_ROLE_ANALYTICS_CAN_ACCESS_CUSTOM_REPORTS,
//     ID_ROLE_ANALYTICS_CAN_ACCESS_OUTREACH_ACTIVITY,
//     ID_ROLE_ANALYTICS_CAN_ACCESS_OUTREACH_KPI,
//     ID_ROLE_ANALYTICS_CAN_ACCESS_LINKEDIN_VIEWED_PROFILES,

//     ID_ROLE_SUBSCRIPTION,
//     ID_ROLE_SUBSCRIPTION_USAGE,
//     ID_ROLE_SUBSCRIPTION_MANAGE_PLAN_BILLING
// } from "./IDs";


// // Admin
// export const PLATFORM_DIRECT_SOURCING: boolean = userLocalData.adminSettings(ID_PLATFORM_DIRECT_SOURCING);
// export const PLATFORM_HIGH_VOLUME_HIRING: boolean = userLocalData.adminSettings(ID_PLATFORM_HIGH_VOLUME_HIRING);
// export const PLATFORM_TALENT_SOURCE: boolean = userLocalData.adminSettings(ID_PLATFORM_TALENT_SOURCE);
// export const PLATFORM_STAFFING: boolean = userLocalData.adminSettings(ID_PLATFORM_STAFFING);
// export const PLATFORM_ADHOC: boolean = userLocalData.adminSettings(ID_PLATFORM_ADHOC);

// export const CORE_JOBS: boolean = userLocalData.adminSettings(ID_CORE_JOBS);
// export const CORE_CANDIDATES: boolean = userLocalData.adminSettings(ID_CORE_CANDIDATES);
// export const CORE_CLIENTS: boolean = userLocalData.adminSettings(ID_CORE_CLIENTS);
// export const CORE_CONTACTS: boolean = userLocalData.adminSettings(ID_CORE_CONTACTS);

// export const ADDON_CAREER_PORTAL: boolean = userLocalData.adminSettings(ID_ADDON_CAREER_PORTAL);
// export const ADDON_CHATBOT: boolean = userLocalData.adminSettings(ID_ADDON_CHATBOT);
// export const ADDON_PROJECTS_TALENTPOOL: boolean = userLocalData.adminSettings(ID_ADDON_PROJECTS_TALENTPOOL);
// export const ADDON_REFERRAL: boolean = userLocalData.adminSettings(ID_ADDON_REFERRAL);
// export const ADDON_SMS: boolean = userLocalData.adminSettings(ID_ADDON_SMS);
// export const ADDON_CHROME_EXTENSION: boolean = userLocalData.adminSettings(ID_ADDON_CHROME_EXTENSION);
// export const ADDON_PUBLIC_TALENT_CLOUD: boolean = userLocalData.adminSettings(ID_ADDON_PUBLIC_TALENT_CLOUD);
// export const ADDON_DOCUMENT_SIGNING: boolean = userLocalData.adminSettings(ID_ADDON_DOCUMENT_SIGNING);
// export const ADDON_PEOPLE_CONTACT: boolean = userLocalData.adminSettings(ID_ADDON_PEOPLE_CONTACT);
// export const ADDON_PEOPLE_CANDIDATE: boolean = userLocalData.adminSettings(ID_ADDON_PEOPLE_CANDIDATE);
// export const ADDON_SYSTEM_CHECKER: boolean = userLocalData.adminSettings(ID_ADDON_SYSTEM_CHECKER);
// export const ADDON_IDIBU: boolean = userLocalData.adminSettings(ID_ADDON_IDIBU);
// export const ADDON_JOBTARGET: boolean = userLocalData.adminSettings(ID_ADDON_JOBTARGET);
// export const ADDON_JOB_ICON: boolean = userLocalData.adminSettings(ID_ADDON_JOB_ICON);

// export const SETTINGS_APPLICANTS: boolean = userLocalData.adminSettings(ID_SETTINGS_APPLICANTS);
// export const SETTINGS_COMMUNITY: boolean = userLocalData.adminSettings(ID_SETTINGS_COMMUNITY);
// export const SETTINGS_TALENTPOOL: boolean = userLocalData.adminSettings(ID_SETTINGS_TALENTPOOL);
// export const SETTINGS_RESUMES: boolean = userLocalData.adminSettings(ID_SETTINGS_RESUMES);
// export const SETTINGS_PEOPLE: boolean = userLocalData.adminSettings(ID_SETTINGS_PEOPLE);
// export const SETTINGS_FORMS: boolean = userLocalData.adminSettings(ID_SETTINGS_FORMS);
// export const SETTINGS_CAMPAIGNS: boolean = userLocalData.adminSettings(ID_SETTINGS_CAMPAIGNS);
// export const SETTINGS_WORKFLOW: boolean = userLocalData.adminSettings(ID_SETTINGS_WORKFLOW);
// export const SETTINGS_EMAILBUILDER: boolean = userLocalData.adminSettings(ID_SETTINGS_EMAILBUILDER);
// export const SETTINGS_HIRING_WORKFLOW: boolean = userLocalData.adminSettings(ID_SETTINGS_HIRING_WORKFLOW);
// export const SETTINGS_JOURNEYS: boolean = userLocalData.adminSettings(ID_SETTINGS_JOURNEYS);
// export const SETTINGS_EVALUTE: boolean = userLocalData.adminSettings(ID_SETTINGS_EVALUTE);
// export const SETTINGS_SOVREN: boolean = userLocalData.adminSettings(ID_SETTINGS_SOVREN);
// export const SETTINGS_PEOPLE_LOCATION_ALL: boolean = userLocalData.adminSettings(ID_SETTINGS_PEOPLE_LOCATION_ALL);
// export const SETTINGS_PEOPLE_LOCATION_US: boolean = userLocalData.adminSettings(ID_SETTINGS_PEOPLE_LOCATION_US);
// export const SETTINGS_SENDGRID: boolean = userLocalData.adminSettings(ID_SETTINGS_SENDGRID);
// export const SETTINGS_QUICK_ACTION: boolean = userLocalData.adminSettings(ID_SETTINGS_QUICK_ACTION);


// export const REPORTS_TALENT_COMMUNITY_INSIGHTS: boolean = userLocalData.adminSettings(ID_REPORTS_TALENT_COMMUNITY_INSIGHTS);
// export const REPORTS_EXECUTIVE_INSIGHTS: boolean = userLocalData.adminSettings(ID_REPORTS_EXECUTIVE_INSIGHTS);
// export const REPORTS_HIRING_INSIGHTS: boolean = userLocalData.adminSettings(ID_REPORTS_HIRING_INSIGHTS);
// export const REPORTS_SOURCING_INSIGHTS: boolean = userLocalData.adminSettings(ID_REPORTS_SOURCING_INSIGHTS);
// export const REPORTS_PIPELINE_INSIGHTS: boolean = userLocalData.adminSettings(ID_REPORTS_PIPELINE_INSIGHTS);
// export const REPORTS_RECRUITER_ACTIVITY_INSIGHTS: boolean = userLocalData.adminSettings(ID_REPORTS_RECRUITER_ACTIVITY_INSIGHTS);
// export const REPORTS_CREATE_DASHBOARD: boolean = userLocalData.adminSettings(ID_REPORTS_CREATE_DASHBOARD);
// export const REPORTS_AI_DATA_ANALYST: boolean = userLocalData.adminSettings(ID_REPORTS_AI_DATA_ANALYST);
// export const REPORTS_CUSTOM_REPORT: boolean = userLocalData.adminSettings(ID_REPORTS_CUSTOM_REPORT);
// export const REPORTS_OUTREACH_ACTIVITY: boolean = userLocalData.adminSettings(ID_REPORTS_OUTREACH_ACTIVITY);
// export const REPORTS_OUTREACH_KPI: boolean = userLocalData.adminSettings(ID_REPORTS_OUTREACH_KPI);
// export const REPORTS_LINKEDIN_VIEWED_PROFILES: boolean = userLocalData.adminSettings(ID_REPORTS_LINKEDIN_VIEWED_PROFILES);



// export const ATS_BULLHORN: boolean = userLocalData.adminSettings(ID_ATS_BULLHORN);
// export const ATS_VOICEAI: boolean = userLocalData.adminSettings(ID_ATS_VOICEAI);
// export const ATS_AVIONTEAPI: boolean = userLocalData.adminSettings(ID_ATS_AVIONTEAPI);
// export const ATS_JOBDIVA: boolean = userLocalData.adminSettings(ID_ATS_JOBDIVA);

// // Admin


// // Role
// export const ROLE_ADMIN_SETTINGS: boolean = userLocalData.checkSettings(ID_ROLE_ADMIN_SETTINGS);
// export const ROLE_ADMIN_SETTINGS_USER: boolean = userLocalData.checkSettings(ID_ROLE_ADMIN_SETTINGS_USER);
// export const ROLE_ADMIN_SETTINGS_ROLE: boolean = userLocalData.checkSettings(ID_ROLE_ADMIN_SETTINGS_ROLE);

// export const ROLE_COMPANY_SETTINGS: boolean = userLocalData.checkSettings(ID_ROLE_COMPANY_SETTINGS);
// export const ROLE_COMPANY_SETTINGS_BRAND: boolean = userLocalData.checkSettings(ID_ROLE_COMPANY_SETTINGS_BRAND);
// export const ROLE_COMPANY_SETTINGS_GOALS: boolean = userLocalData.checkSettings(ID_ROLE_COMPANY_SETTINGS_GOALS);
// export const ROLE_COMPANY_SETTINGS_CAREER_PORTAL: boolean = userLocalData.checkSettings(ID_ROLE_COMPANY_SETTINGS_CAREER_PORTAL);
// export const ROLE_COMPANY_SETTINGS_ORGANIZATION: boolean = userLocalData.checkSettings(ID_ROLE_COMPANY_SETTINGS_ORGANIZATION);
// export const ROLE_COMPANY_SETTINGS_SOURCES: boolean = userLocalData.checkSettings(ID_ROLE_COMPANY_SETTINGS_SOURCES);
// export const ROLE_COMPANY_SETTINGS_SENDING_LIMIT: boolean = userLocalData.checkSettings(ID_ROLE_COMPANY_SETTINGS_SENDING_LIMIT);
// export const ROLE_COMPANY_SETTINGS_SEQUENCE_RULESET: boolean = userLocalData.checkSettings(ID_ROLE_COMPANY_SETTINGS_SEQUENCE_RULESET);
// export const ROLE_COMPANY_SETTINGS_COMMUNITY_: boolean = userLocalData.checkSettings(ID_ROLE_COMPANY_SETTINGS_COMMUNITY);
// export const ROLE_COMPANY_SETTINGS_REFERRAL: boolean = userLocalData.checkSettings(ID_ROLE_COMPANY_SETTINGS_REFERRAL);

// export const ROLE_DEVELOPER_SETTINGS: boolean = userLocalData.checkSettings(ID_ROLE_DEVELOPER_SETTINGS);
// export const ROLE_DEVELOPER_SETTINGS_WEBHOOK: boolean = userLocalData.checkSettings(ID_ROLE_DEVELOPER_SETTINGS_WEBHOOK);
// export const ROLE_DEVELOPER_SETTINGS_API: boolean = userLocalData.checkSettings(ID_ROLE_DEVELOPER_SETTINGS_API);

// export const ROLE_APP_SETTINGS: boolean = userLocalData.checkSettings(ID_ROLE_APP_SETTINGS);
// export const ROLE_APP_SETTINGS_MESSAGE_TEMPLATES: boolean = userLocalData.checkSettings(ID_ROLE_APP_SETTINGS_MESSAGE_TEMPLATES);
// export const ROLE_APP_SETTINGS_CUSTOM_FIELDS: boolean = userLocalData.checkSettings(ID_ROLE_APP_SETTINGS_CUSTOM_FIELDS);
// export const ROLE_APP_SETTINGS_REASONS: boolean = userLocalData.checkSettings(ID_ROLE_APP_SETTINGS_REASONS);
// export const ROLE_APP_SETTINGS_OPTION_BANKS: boolean = userLocalData.checkSettings(ID_ROLE_APP_SETTINGS_OPTION_BANKS);
// export const ROLE_APP_SETTINGS_DUPLICATE_SETTINGS: boolean = userLocalData.checkSettings(ID_ROLE_APP_SETTINGS_DUPLICATE_SETTINGS);
// export const ROLE_APP_SETTINGS_SCORE: boolean = userLocalData.checkSettings(ID_ROLE_APP_SETTINGS_SCORE);
// export const ROLE_APP_SETTINGS_GOALS: boolean = userLocalData.checkSettings(ID_ROLE_APP_SETTINGS_GOALS);
// export const ROLE_APP_SETTINGS_HOLIDAY_SETTING: boolean = userLocalData.checkSettings(ID_ROLE_APP_SETTINGS_HOLIDAY_SETTING);




// export const ROLE_JOB_MODULE: boolean = userLocalData.checkIntegration(ID_ROLE_JOB_MODULE);
// export const ROLE_JOB_ALLOW_TO_CREATE_NEW_JOB: boolean = userLocalData.checkIntegration(ID_ROLE_JOB_ALLOW_TO_CREATE_NEW_JOB);
// export const ROLE_JOB_ALLOW_TO_DELETE_JOB: boolean = userLocalData.checkIntegration(ID_ROLE_JOB_ALLOW_TO_DELETE_JOB);
// export const ROLE_JOB_ALLOW_TO_MERGE_JOBS: boolean = userLocalData.checkIntegration(ID_ROLE_JOB_ALLOW_TO_MERGE_JOBS);
// export const ROLE_JOB_ALLOW_TO_POST_JOBS_ON_INTERNAL_AND_EXTERNAL_SITES: boolean = userLocalData.checkIntegration(ID_ROLE_JOB_ALLOW_TO_POST_JOBS_ON_INTERNAL_AND_EXTERNAL_SITES);

// export const ROLE_CANDIDATE_MODULE: boolean = userLocalData.checkIntegration(ID_ROLE_CANDIDATE_MODULE);
// export const ROLE_CANDIDATE_CAN_CREATE_NEW_CANDIDATE: boolean = userLocalData.checkIntegration(ID_ROLE_CANDIDATE_CAN_CREATE_NEW_CANDIDATE);
// export const ROLE_CANDIDATE_CAN_CREATE_TALENT_POOLS: boolean = userLocalData.checkIntegration(ID_ROLE_CANDIDATE_CAN_CREATE_TALENT_POOLS);
// export const ROLE_CANDIDATE_CAN_VIEW_EDIT_TALENT_POOLS_INCLUDING_PRIVATE: boolean = userLocalData.checkIntegration(ID_ROLE_CANDIDATE_CAN_VIEW_EDIT_TALENT_POOLS_INCLUDING_PRIVATE);
// export const ROLE_CANDIDATE_CAN_SEARCH_IN_TALENT_COMMUNITY: boolean = userLocalData.checkIntegration(ID_ROLE_CANDIDATE_CAN_SEARCH_IN_TALENT_COMMUNITY);
// export const ROLE_CANDIDATE_CAN_SEARCH_EXTERNAL_JOB_BOARDS: boolean = userLocalData.checkIntegration(ID_ROLE_CANDIDATE_CAN_SEARCH_EXTERNAL_JOB_BOARDS);
// export const ROLE_CANDIDATE_CAN_SEARCH_PUBLIC_TALENT_POOL: boolean = userLocalData.checkIntegration(ID_ROLE_CANDIDATE_CAN_SEARCH_PUBLIC_TALENT_POOL);

// export const ROLE_CONTACT_MODULE: boolean = userLocalData.checkIntegration(ID_ROLE_CONTACT_MODULE);
// export const ROLE_CONTACT_CAN_CREATE_NEW_CONTACT: boolean = userLocalData.checkIntegration(ID_ROLE_CONTACT_CAN_CREATE_NEW_CONTACT);
// export const ROLE_CONTACT_CAN_EDIT_CONTACT: boolean = userLocalData.checkIntegration(ID_ROLE_CONTACT_CAN_EDIT_CONTACT);
// export const ROLE_CONTACT_CAN_MERGE_CONTACT: boolean = userLocalData.checkIntegration(ID_ROLE_CONTACT_CAN_MERGE_CONTACT);
// export const ROLE_CONTACT_CAN_VIEW_TASKS_NOTES_ACTIVITY_LOGS_OF_ALL_USERS: boolean = userLocalData.checkIntegration(ID_ROLE_CONTACT_CAN_VIEW_TASKS_NOTES_ACTIVITY_LOGS_OF_ALL_USERS);
// export const ROLE_CONTACT_CAN_EDIT_TASKS_NOTES_ACTIVITY_LOGS_OF_ALL_USERS: boolean = userLocalData.checkIntegration(ID_ROLE_CONTACT_CAN_EDIT_TASKS_NOTES_ACTIVITY_LOGS_OF_ALL_USERS);
// export const ROLE_CONTACT_CAN_VIEW_CONTACT: boolean = userLocalData.checkIntegration(ID_ROLE_CONTACT_CAN_VIEW_CONTACT);

// export const ROLE_CLIENT_MODULE: boolean = userLocalData.checkIntegration(ID_ROLE_CLIENT_MODULE);
// export const ROLE_CLIENT_CAN_CREATE_NEW_CLIENT: boolean = userLocalData.checkIntegration(ID_ROLE_CLIENT_CAN_CREATE_NEW_CLIENT);
// export const ROLE_CLIENT_CAN_MERGE_CLIENTS: boolean = userLocalData.checkIntegration(ID_ROLE_CLIENT_CAN_MERGE_CLIENTS);
// export const ROLE_CLIENT_CAN_VIEW_ALL_CLIENTS: boolean = userLocalData.checkIntegration(ID_ROLE_CLIENT_CAN_VIEW_ALL_CLIENTS);
// export const ROLE_CLIENT_CAN_VIEW_ONLY_CLIENTS_ASSIGNED_TO_THEM: boolean = userLocalData.checkIntegration(ID_ROLE_CLIENT_CAN_VIEW_ONLY_CLIENTS_ASSIGNED_TO_THEM);

// export const ROLE_EMAIL_AND_SMS: boolean = userLocalData.checkIntegration(ID_ROLE_EMAIL_AND_SMS);
// export const ROLE_EMAIL_AND_SMS_CAN_SEND_BULK_EMAIL: boolean = userLocalData.checkIntegration(ID_ROLE_EMAIL_AND_SMS_CAN_SEND_BULK_EMAIL);
// export const ROLE_EMAIL_AND_SMS_CAN_SEND_BULK_SMS: boolean = userLocalData.checkIntegration(ID_ROLE_EMAIL_AND_SMS_CAN_SEND_BULK_SMS);
// export const ROLE_EMAIL_AND_SMS_CAN_SEND_EMAIL_ON_BEHALF_OF_OTHER_USERS: boolean = userLocalData.checkIntegration(ID_ROLE_EMAIL_AND_SMS_CAN_SEND_EMAIL_ON_BEHALF_OF_OTHER_USERS);
// export const ROLE_EMAIL_AND_SMS_CAN_SEND_SMS_ON_BEHALF_OF_OTHER_USERS: boolean = userLocalData.checkIntegration(ID_ROLE_EMAIL_AND_SMS_CAN_SEND_SMS_ON_BEHALF_OF_OTHER_USERS);
// export const ROLE_EMAIL_AND_SMS_CAN_EDIT_VIEW_MESSAGE_TEMPLATES: boolean = userLocalData.checkIntegration(ID_ROLE_EMAIL_AND_SMS_CAN_EDIT_VIEW_MESSAGE_TEMPLATES);
// export const ROLE_EMAIL_AND_SMS_CAN_EDIT_DELETE_MESSAGE_TEMPLATES: boolean = userLocalData.checkIntegration(ID_ROLE_EMAIL_AND_SMS_CAN_EDIT_DELETE_MESSAGE_TEMPLATES);


// export const ROLE_PEOPLE: boolean = userLocalData.checkIntegration(ID_ROLE_PEOPLE);
// export const ROLE_PEOPLE_CAN_SEARCH_TALENT_DIRECTORY: boolean = userLocalData.checkIntegration(ID_ROLE_PEOPLE_CAN_SEARCH_TALENT_DIRECTORY);
// export const ROLE_PEOPLE_CAN_ADD_EDIT_PERSONAS: boolean = userLocalData.checkIntegration(ID_ROLE_PEOPLE_CAN_ADD_EDIT_PERSONAS);
// export const ROLE_PEOPLE_CAN_REQUEST_EMAIL_CONTACT: boolean = userLocalData.checkIntegration(ID_ROLE_PEOPLE_CAN_REQUEST_EMAIL_CONTACT);
// export const ROLE_PEOPLE_CAN_REQUEST_MOBILE_CONTACT_: boolean = userLocalData.checkIntegration(ID_ROLE_PEOPLE_CAN_REQUEST_MOBILE_CONTACT_);
// export const ROLE_PEOPLE_CAN_BULK_REQUEST_MOBILE_CONTACT: boolean = userLocalData.checkIntegration(ID_ROLE_PEOPLE_CAN_BULK_REQUEST_MOBILE_CONTACT);
// export const ROLE_PEOPLE_CAN_BULK_REQUEST_EMAIL_CONTACT: boolean = userLocalData.checkIntegration(ID_ROLE_PEOPLE_CAN_BULK_REQUEST_EMAIL_CONTACT);

// export const ROLE_ANALYTICS: boolean = userLocalData.checkIntegration(ID_ROLE_ANALYTICS);
// export const ROLE_ANALYTICS_CAN_ACCESS_EXECUTIVE_INSIGHTS: boolean = userLocalData.checkIntegration(ID_ROLE_ANALYTICS_CAN_ACCESS_EXECUTIVE_INSIGHTS);
// export const ROLE_ANALYTICS_CAN_ACCESS_HIRING_INSIGHTS: boolean = userLocalData.checkIntegration(ID_ROLE_ANALYTICS_CAN_ACCESS_HIRING_INSIGHTS);
// export const ROLE_ANALYTICS_CAN_ACCESS_RECRUITER_ACTIVITY_INSIGHTS: boolean = userLocalData.checkIntegration(ID_ROLE_ANALYTICS_CAN_ACCESS_RECRUITER_ACTIVITY_INSIGHTS);
// export const ROLE_ANALYTICS_CAN_ACCESS_SOURCING_INSIGHTS: boolean = userLocalData.checkIntegration(ID_ROLE_ANALYTICS_CAN_ACCESS_SOURCING_INSIGHTS);
// export const ROLE_ANALYTICS_CAN_ACCESS_APPLICANT_INSIGHTS: boolean = userLocalData.checkIntegration(ID_ROLE_ANALYTICS_CAN_ACCESS_APPLICANT_INSIGHTS);
// export const ROLE_ANALYTICS_CAN_ACCESS_TALENT_COMMUNITY_INSIGHTS: boolean = userLocalData.checkIntegration(ID_ROLE_ANALYTICS_CAN_ACCESS_TALENT_COMMUNITY_INSIGHTS);
// export const ROLE_ANALYTICS_CAN_ACCESS_PIPELINE_INSIGHTS: boolean = userLocalData.checkIntegration(ID_ROLE_ANALYTICS_CAN_ACCESS_PIPELINE_INSIGHTS);
// export const ROLE_ANALYTICS_CAN_ACCESS_CUSTOM_REPORTS: boolean = userLocalData.checkIntegration(ID_ROLE_ANALYTICS_CAN_ACCESS_CUSTOM_REPORTS);
// export const ROLE_ANALYTICS_CAN_ACCESS_OUTREACH_ACTIVITY: boolean = userLocalData.checkIntegration(ID_ROLE_ANALYTICS_CAN_ACCESS_OUTREACH_ACTIVITY);
// export const ROLE_ANALYTICS_CAN_ACCESS_OUTREACH_KPI: boolean = userLocalData.checkIntegration(ID_ROLE_ANALYTICS_CAN_ACCESS_OUTREACH_KPI);
// export const ROLE_ANALYTICS_CAN_ACCESS_LINKEDIN_VIEWED_PROFILES: boolean = userLocalData.checkIntegration(ID_ROLE_ANALYTICS_CAN_ACCESS_LINKEDIN_VIEWED_PROFILES);



// export const ROLE_SUBSCRIPTION: boolean = userLocalData.checkIntegration(ID_ROLE_SUBSCRIPTION);
// export const ROLE_SUBSCRIPTION_USAGE: boolean = ROLE_SUBSCRIPTION && userLocalData.checkIntegration(ID_ROLE_SUBSCRIPTION_USAGE);
// export const ROLE_SUBSCRIPTION_MANAGE_PLAN_BILLING: boolean = ROLE_SUBSCRIPTION && userLocalData.checkIntegration(ID_ROLE_SUBSCRIPTION_MANAGE_PLAN_BILLING);

// // Role