
// Admin
export const ID_PLATFORM_DIRECT_SOURCING = 30001;
export const ID_PLATFORM_HIGH_VOLUME_HIRING = 30002;
export const ID_PLATFORM_TALENT_SOURCE = 30003;
export const ID_PLATFORM_STAFFING = 30004;
export const ID_PLATFORM_ADHOC = 30005;

export const ID_CORE_JOBS = 20001;
export const ID_CORE_CANDIDATES = 20002;
export const ID_CORE_CLIENTS = 20003;
export const ID_CORE_CONTACTS = 20004;

export const ID_ADDON_CAREER_PORTAL = 20005;
export const ID_ADDON_CHATBOT = 20006;
export const ID_ADDON_PROJECTS_TALENTPOOL = 20007;
export const ID_ADDON_REFERRAL = 20008;
export const ID_ADDON_SMS = 20009;
export const ID_ADDON_CHROME_EXTENSION = 20010;
export const ID_ADDON_PUBLIC_TALENT_CLOUD = 20011;
export const ID_ADDON_DOCUMENT_SIGNING = 20012;
export const ID_ADDON_PEOPLE_CONTACT = 20013;
export const ID_ADDON_PEOPLE_CANDIDATE = 20014;
export const ID_ADDON_SYSTEM_CHECKER = 20015;
export const ID_ADDON_IDIBU = 20016;
export const ID_ADDON_JOBTARGET = 20017;
export const ID_ADDON_JOB_ICON = 20040;

export const ID_SETTINGS_APPLICANTS = 20018;
export const ID_SETTINGS_COMMUNITY = 20019;
export const ID_SETTINGS_TALENTPOOL = 20020;
export const ID_SETTINGS_RESUMES = 20021;
export const ID_SETTINGS_PEOPLE = 20022;
export const ID_SETTINGS_FORMS = 20023;
export const ID_SETTINGS_CAMPAIGNS = 20024;
export const ID_SETTINGS_WORKFLOW = 20025;
export const ID_SETTINGS_EMAILBUILDER = 20026;
export const ID_SETTINGS_HIRING_WORKFLOW = 20027;
export const ID_SETTINGS_JOURNEYS = 20028;
export const ID_SETTINGS_EVALUTE = 20046;
export const ID_SETTINGS_SOVREN = 20048;
export const ID_SETTINGS_PEOPLE_LOCATION_ALL = 20041;
export const ID_SETTINGS_PEOPLE_LOCATION_US = 20042;
export const ID_SETTINGS_SENDGRID = 20052;
export const ID_SETTINGS_QUICK_ACTION = 20053;
export const ID_SETTINGS_FORMATJD = 20054;

export const ID_REPORTS_TALENT_COMMUNITY_INSIGHTS = 20029;
export const ID_REPORTS_EXECUTIVE_INSIGHTS = 20030;
export const ID_REPORTS_HIRING_INSIGHTS = 20031;
export const ID_REPORTS_SOURCING_INSIGHTS = 20032;
export const ID_REPORTS_PIPELINE_INSIGHTS = 20033;
export const ID_REPORTS_RECRUITER_ACTIVITY_INSIGHTS = 20034;
export const ID_REPORTS_CREATE_DASHBOARD = 20035;
export const ID_REPORTS_AI_DATA_ANALYST = 20036;
export const ID_REPORTS_CUSTOM_REPORT = 20037;
export const ID_REPORTS_OUTREACH_ACTIVITY = 20049;
export const ID_REPORTS_OUTREACH_KPI = 20050;
export const ID_REPORTS_LINKEDIN_VIEWED_PROFILES = 20051;



export const ID_ATS_BULLHORN = 20043;
export const ID_ATS_VOICEAI = 20044;
export const ID_ATS_AVIONTEAPI = 20045;
export const ID_ATS_JOBDIVA = 20047;

// Admin


// Role
export const ID_ROLE_ADMIN_SETTINGS = 10001;
export const ID_ROLE_ADMIN_SETTINGS_USER = 100001;
export const ID_ROLE_ADMIN_SETTINGS_ROLE = 100002;

export const ID_ROLE_COMPANY_SETTINGS = 10002;
export const ID_ROLE_COMPANY_SETTINGS_BRAND = 110001;
export const ID_ROLE_COMPANY_SETTINGS_GOALS = 110002;
export const ID_ROLE_COMPANY_SETTINGS_CAREER_PORTAL = 110003;
export const ID_ROLE_COMPANY_SETTINGS_ORGANIZATION = 110004;
export const ID_ROLE_COMPANY_SETTINGS_SOURCES = 110005;
export const ID_ROLE_COMPANY_SETTINGS_SENDING_LIMIT = 110006;
export const ID_ROLE_COMPANY_SETTINGS_SEQUENCE_RULESET = 110007;
export const ID_ROLE_COMPANY_SETTINGS_COMMUNITY = 110008;
export const ID_ROLE_COMPANY_SETTINGS_REFERRAL = 110009;

export const ID_ROLE_DEVELOPER_SETTINGS = 10003;
export const ID_ROLE_DEVELOPER_SETTINGS_WEBHOOK = 120001;
export const ID_ROLE_DEVELOPER_SETTINGS_API = 120002;

export const ID_ROLE_APP_SETTINGS = 10004;
export const ID_ROLE_APP_SETTINGS_MESSAGE_TEMPLATES = 130001;
export const ID_ROLE_APP_SETTINGS_CUSTOM_FIELDS = 130002;
export const ID_ROLE_APP_SETTINGS_REASONS = 130003;
export const ID_ROLE_APP_SETTINGS_OPTION_BANKS = 130004;
export const ID_ROLE_APP_SETTINGS_DUPLICATE_SETTINGS = 130005;
export const ID_ROLE_APP_SETTINGS_SCORE = 130006;
export const ID_ROLE_APP_SETTINGS_GOALS = 130007;
export const ID_ROLE_APP_SETTINGS_HOLIDAY_SETTING = 130008;

export const ID_ROLE_JOB_MODULE = 40001;
export const ID_ROLE_JOB_ALLOW_TO_CREATE_NEW_JOB = 400001;
export const ID_ROLE_JOB_ALLOW_TO_DELETE_JOB = 400002;
export const ID_ROLE_JOB_ALLOW_TO_MERGE_JOBS = 400003;
export const ID_ROLE_JOB_ALLOW_TO_POST_JOBS_ON_INTERNAL_AND_EXTERNAL_SITES = 400004;

export const ID_ROLE_CANDIDATE_MODULE = 40002;
export const ID_ROLE_CANDIDATE_CAN_CREATE_NEW_CANDIDATE = 400005;
export const ID_ROLE_CANDIDATE_CAN_CREATE_TALENT_POOLS = 400006;
export const ID_ROLE_CANDIDATE_CAN_VIEW_EDIT_TALENT_POOLS_INCLUDING_PRIVATE = 400007;
export const ID_ROLE_CANDIDATE_CAN_SEARCH_IN_TALENT_COMMUNITY = 400008;
export const ID_ROLE_CANDIDATE_CAN_SEARCH_EXTERNAL_JOB_BOARDS = 400009;
export const ID_ROLE_CANDIDATE_CAN_SEARCH_PUBLIC_TALENT_POOL = 400010;

export const ID_ROLE_CONTACT_MODULE = 40003;
export const ID_ROLE_CONTACT_CAN_CREATE_NEW_CONTACT = 400011;
export const ID_ROLE_CONTACT_CAN_EDIT_CONTACT = 400012;
export const ID_ROLE_CONTACT_CAN_MERGE_CONTACT = 400013;
export const ID_ROLE_CONTACT_CAN_VIEW_TASKS_NOTES_ACTIVITY_LOGS_OF_ALL_USERS = 400014;
export const ID_ROLE_CONTACT_CAN_EDIT_TASKS_NOTES_ACTIVITY_LOGS_OF_ALL_USERS = 400015;
export const ID_ROLE_CONTACT_CAN_VIEW_CONTACT = 400040;

export const ID_ROLE_CLIENT_MODULE = 40004;
export const ID_ROLE_CLIENT_CAN_CREATE_NEW_CLIENT = 400016;
export const ID_ROLE_CLIENT_CAN_MERGE_CLIENTS = 400017;
export const ID_ROLE_CLIENT_CAN_VIEW_ALL_CLIENTS = 400018;
export const ID_ROLE_CLIENT_CAN_VIEW_ONLY_CLIENTS_ASSIGNED_TO_THEM = 400019;

export const ID_ROLE_EMAIL_AND_SMS = 40005;
export const ID_ROLE_EMAIL_AND_SMS_CAN_SEND_BULK_EMAIL = 400020;
export const ID_ROLE_EMAIL_AND_SMS_CAN_SEND_BULK_SMS = 400021;
export const ID_ROLE_EMAIL_AND_SMS_CAN_SEND_EMAIL_ON_BEHALF_OF_OTHER_USERS = 400022;
export const ID_ROLE_EMAIL_AND_SMS_CAN_SEND_SMS_ON_BEHALF_OF_OTHER_USERS = 400023;
export const ID_ROLE_EMAIL_AND_SMS_CAN_EDIT_VIEW_MESSAGE_TEMPLATES = 400044;
export const ID_ROLE_EMAIL_AND_SMS_CAN_EDIT_DELETE_MESSAGE_TEMPLATES = 400045;
export const ID_ROLE_EMAIL_AND_SMS_CAN_ENABLE_EMAILBUILDER = 400047; 
 

export const ID_ROLE_PEOPLE = 40006;
export const ID_ROLE_PEOPLE_CAN_SEARCH_TALENT_DIRECTORY = 400024;
export const ID_ROLE_PEOPLE_CAN_ADD_EDIT_PERSONAS = 400025;
export const ID_ROLE_PEOPLE_CAN_REQUEST_EMAIL_CONTACT = 400026;
export const ID_ROLE_PEOPLE_CAN_REQUEST_MOBILE_CONTACT_ = 400027;
export const ID_ROLE_PEOPLE_CAN_BULK_REQUEST_MOBILE_CONTACT = 400028;
export const ID_ROLE_PEOPLE_CAN_BULK_REQUEST_EMAIL_CONTACT = 400029;

export const ID_ROLE_ANALYTICS = 40007;
export const ID_ROLE_ANALYTICS_CAN_ACCESS_EXECUTIVE_INSIGHTS = 400030;
export const ID_ROLE_ANALYTICS_CAN_ACCESS_HIRING_INSIGHTS = 400031;
export const ID_ROLE_ANALYTICS_CAN_ACCESS_RECRUITER_ACTIVITY_INSIGHTS = 400032;
export const ID_ROLE_ANALYTICS_CAN_ACCESS_SOURCING_INSIGHTS = 400033;
export const ID_ROLE_ANALYTICS_CAN_ACCESS_APPLICANT_INSIGHTS = 400034;
export const ID_ROLE_ANALYTICS_CAN_ACCESS_TALENT_COMMUNITY_INSIGHTS = 400035;
export const ID_ROLE_ANALYTICS_CAN_ACCESS_PIPELINE_INSIGHTS = 400036;
export const ID_ROLE_ANALYTICS_CAN_ACCESS_CUSTOM_REPORTS = 400037;
export const ID_ROLE_ANALYTICS_CAN_ACCESS_OUTREACH_ACTIVITY = 400041;
export const ID_ROLE_ANALYTICS_CAN_ACCESS_OUTREACH_KPI = 400042;
export const ID_ROLE_ANALYTICS_CAN_ACCESS_LINKEDIN_VIEWED_PROFILES = 400043;


export const ID_ROLE_SUBSCRIPTION = 40008;
export const ID_ROLE_SUBSCRIPTION_USAGE = 400038;
export const ID_ROLE_SUBSCRIPTION_MANAGE_PLAN_BILLING = 400039;

// Role